#Section 01. 넘파이 소개
## 1. 넘파이 개념

In [3]:
# 주피터 노트북 사용자
# !pip install numpy

In [4]:
import numpy as np # numpy의 별칭을 np로 설정
print(np.__version__) # 파이썬 라이브러리의 버전 확인

2.2.4


##2. 넘파이 배열

In [5]:
d=np.arange(12).reshape(3,4)
print(d,d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


###dtype

In [6]:
print(d.dtype)

int64


###ndim

In [7]:
print(d.ndim) #차원

2


###T

In [8]:
print(d.T) # 전치 행렬

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


###size

In [9]:
print(d.size) # 요소의 개수

12


###nbtypes

In [10]:
print(d.nbytes) # 64bit는 8byte이므로 총 96byte(8*12)

96


### flat

In [11]:
d.flat=1
print(d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


##3. 넘파이 배열 생성
##리스트로 생성
- 형 변환
- 리스트 -> 넘파이배열로 변환

In [12]:
mynpa1=np.array([1, 2, 3])
print(type(mynpa1))

<class 'numpy.ndarray'>


In [13]:
mylist2=[[1, 2, 3],
 [4, 5, 6]]
print(type(mylist2))
mynpa2=np.array(mylist2) # 변수명 직접 입력
print(type(mynpa2))

<class 'list'>
<class 'numpy.ndarray'>


###데이터프레임으로 생성

In [14]:
import pandas as pd
mypd1=pd.DataFrame([1, 2, 3])
print(type(mypd1))
mynp1=np.array(mypd1)
print(type(mynp1))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [15]:
mylist2=[[1, 2, 3],
 [4, 5, 6]]
print(type(mylist2))
mypd2=pd.DataFrame(mylist2)
print(type(mypd2))
mynpa2=np.array(mypd2)
print(type(mynpa2))
mypd2

<class 'list'>
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


0  1  2
0  1  2  3
1  4  5  6

##4. n차원 넘파이 배열
##5. 1차원 넘파이 배열 생성


In [16]:
import numpy as np
a=np.arange(3)
print(a, type(a), a.ndim, a.shape)

[0 1 2] <class 'numpy.ndarray'> 1 (3,)


####① 종료값만 설정

In [17]:
a2=np.arange(4)
a2

array([0, 1, 2, 3])

#### ② 시작값, 종료값 설정

In [18]:
a2=np.arange(2, 4)
print(a2, a2.shape)

[2 3] (2,)


####③ 시작값, 종료값, 증가값 모두 설정

In [19]:
a3=np.arange(0, 5, 2)
print(a3, a3.shape)

[0 2 4] (3,)


##6. 2차원 넘파이 배열 생성
### 2행 3열의 배열 생성

In [20]:
m=np.array([[0, 1, 2],
 [3, 4, 5]])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [21]:
m=np.array([np.arange(3), np.arange(3, 6)])
print(m, m.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


###3행 2열의 배열 생성

In [22]:
m=np.array([[0, 3],
 [1, 4],
 [2, 5]])
print(m, m.shape)
print(m.shape[0], m.shape[1])

[[0 3]
 [1 4]
 [2 5]] (3, 2)
3 2


In [23]:
m=np.array([np.arange(0, 4, 3), np.arange(1, 5, 3),
np.arange(2, 6, 3)])
print(m, m.shape)

[[0 3]
 [1 4]
 [2 5]] (3, 2)


##7. 3차원 넘파이 배열 생성

In [24]:
m=np.array([[[0, 1, 2],
 [3, 4, 5]],
 [[0, 1, 2],
 [3, 4, 5]]])
print(m)
print(m.shape)

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
(2, 2, 3)


In [25]:
m=np.array([[[0, 1],
 [2, 3]],
 [[4, 5],
 [6, 7]],
 [[8, 9],
 [10, 11]]])
print(m, m.shape)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] (3, 2, 2)


In [26]:
m=np.array([[[0, 1, 2]],
 [[3, 4, 5]],
 [[0, 1, 2]],
 [[3, 4, 5]]])
print(m, m.shape)

[[[0 1 2]]

 [[3 4 5]]

 [[0 1 2]]

 [[3 4 5]]] (4, 1, 3)


###<여기서 잠깐> 파이썬의 range 함수와 넘파이의 arange 함수

In [27]:
list=[1, 2, 3, 4, 5]
for i in list:
  print(i)

1
2
3
4
5


In [28]:
list=[1, 2, 3, 4, 5]
for i in range(1, 6):
  print(i)

1
2
3
4
5


In [29]:
list=[1, 2, 3, 4, 5]
for i in range(1, 6, 2):
  print(i)

1
3
5


In [30]:
arr=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [31]:
arr=np.arange(start=1, stop=11, step=1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr=np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr=np.arange(start=1, stop=10, step=2)
arr

array([1, 3, 5, 7, 9])

In [34]:
arr=np.arange(1, 10, 2)
arr

array([1, 3, 5, 7, 9])

# Section 02. 배열 다루기
## 1. 배열의 데이터형 확인과 변형

In [35]:
import numpy as np

nda=np.array([0, 1, 2, 3, 4, 5])
print(nda, type(nda)) # nda 변수의 데이터형 반환
print(nda.dtype) # 넘파이 배열인 nda 요소의 자료형 반환
nda # 넘파이 배열이므로 array([]) 형식으로 표시

[0 1 2 3 4 5] <class 'numpy.ndarray'>
int64


array([0, 1, 2, 3, 4, 5])

In [36]:
nda1=np.array([0, 1, 2, 3.0, 4, 5])
print(nda1, nda1.dtype)

[0. 1. 2. 3. 4. 5.] float64


In [37]:
nda2=np.array([0, 1, 2, 3, 4, 5])
print(nda2, nda2.dtype)

[0 1 2 3 4 5] int64


## 2. 배열의 형태 변경
###배열의 구조 변경하기: reshape 함수

In [38]:
m1=np.arange(6)
print(m1)
print(m1.shape)

[0 1 2 3 4 5]
(6,)


In [39]:
m2=m1.reshape(6, 1)
print(m2, m2.shape) # 1행 6열을 6행 1열로 변경

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [40]:
m2=m1.reshape(2, 3)
print(m2, m2.shape)

[[0 1 2]
 [3 4 5]] (2, 3)


In [41]:
m1=np.arange(12)
m3=m1.reshape(2, 2, 3)
print(m3, m3.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [42]:
m1=np.arange(6)
print(m1, m1.shape)
m2=m1.reshape(-1, 2) # 행 수는 자동, 2열 생성
print(m2, m2.shape)
m2=m1.reshape(-1, 3) # 행 수는 자동, 3열 생성
print(m2, m2.shape)
m2=m1.reshape(-1, 1) # 행 수는 자동, 1열 생성
print(m2, m2.shape)

[0 1 2 3 4 5] (6,)
[[0 1]
 [2 3]
 [4 5]] (3, 2)
[[0 1 2]
 [3 4 5]] (2, 3)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] (6, 1)


In [43]:
m1=np.arange(6)
m3=m1.reshape(-1, 2, 3)
print(m3, m3.shape)
m3=m1.reshape(-1, 3, 2) # 면 수 자동, 3행 2열 생성
print(m3,m3.shape)
m3=m1.reshape(2, 3, -1) # 열 수 자동, 2면 3행 생성
print(m3, m3.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3)
[[[0 1]
  [2 3]
  [4 5]]] (1, 3, 2)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


###다차원 배열을 1차원 배열로 평탄화하기: flatten 함수
-딥러닝 아키텍처
-> Hidden Layer -> output Layer 변환 할때, 반드시 배열을 1차원으로 만들어야 함

In [44]:
a=np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
f=a.flatten()
print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)


###배열의 방향 변경하기

In [46]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
print(a[::-1]) # 행 순서를 거꾸로 변경

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [48]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
print(a[:,::-1]) # 열 순서를 거꾸로 변경

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
print(a[::-1,::-1]) # 행과 열 순서를 거꾸로 변경

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [52]:
t=a.transpose()
print(a, a.shape) # a 배열은 3행 4열
print(t, t.shape) # t 배열은 a 배열을 4행 3열로 변경한 것

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] (4, 3)


In [53]:
print(a.T) # transpose() 함수와 결과 동일

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


##3. 배열 통합과 분할

In [54]:
a=np.arange(9).reshape(3, 3)
b=a*2
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [55]:
r=np.vstack((a, b))
print(r, r.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


In [56]:
#  row_stack 사용 금지
# c=np.row_stack((a, b))
# print(c, c.shape)

In [57]:
x=np.concatenate((a, b), axis=0)
print(x, x.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]] (6, 3)


###열 방향으로 합치기

In [58]:
r=np.hstack((a, b))
print(r, r.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [59]:
c=np.column_stack((a, b))
print(c, c.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


In [60]:
x=np.concatenate((a, b), axis=1)
print(x, x.shape)

[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]] (3, 6)


###행 단위로 분할하기

In [61]:
a=np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [62]:
print(np.vsplit(a, 4))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [63]:
print(np.split(a, 4, axis=0))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [64]:
print(a[0:1], a[1:2], a[2:3], a[3:])

[[0 1 2]] [[3 4 5]] [[6 7 8]] [[ 9 10 11]]


###열 단위로 분할하기

In [65]:
a=np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
print(np.hsplit(a, 4))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [67]:
print(np.split(a, 4, axis=1))

[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


#Section 03. 배열의 인덱싱과 슬라이싱
##1. 1차원 배열의 인덱싱과 슬라이싱

In [68]:
d=np.arange(6)
print(d, d.shape)

[0 1 2 3 4 5] (6,)


In [69]:
# 1차원 배열의 인덱싱
print(d[0], d[1], d[2], d[-1], d[-2])

0 1 2 5 4


In [70]:
# 1차원 배열의 슬라이싱
print(d[2:3], d[:], d[:-1])
print(d[::2], d[::-1])
d[0]=10 # 요소 값 변경
print(d)

[2] [0 1 2 3 4 5] [0 1 2 3 4]
[0 2 4] [5 4 3 2 1 0]
[10  1  2  3  4  5]


##2. 2차원 배열의 인덱싱과 슬라이싱 


In [71]:
d=np.arange(12).reshape(3, 4)
print(d, d.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [72]:
# 2차원 배열의 인덱싱
print(d[0][0]) # 배열명[행][열] 형태
print(d[0,0]) # 배열명[행,열] 형태
print(d[2,1])

0
0
9


In [73]:
# 2차원 배열의 슬라이싱
print(d[0]) # 0행만 슬라이싱
print(d[0,:]) # 0행의 전체 열 슬라이싱
print(d[:,:-1]) # 마지막 열 제외한 전체 행과 열 슬라이싱
print(d[::2,::2]) # 2행 2열 간격으로 전체 행과 열 슬라이싱

[0 1 2 3]
[0 1 2 3]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2]
 [ 8 10]]


In [74]:
d[0]=20 # 0번 행 요소를 모두 20으로 변경
print(d)

[[20 20 20 20]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
d[::2,::3]=30 # 슬라이싱된 요소값을 한꺼번에 변경
print(d[::2,::3])
print(d)

[[30 30]
 [30 30]]
[[30 20 20 30]
 [ 4  5  6  7]
 [30  9 10 30]]


In [76]:
d[:,:]=-1 # 전체 요소값을 한꺼번에 변경
print(d)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


##3. 3차원 배열의 인덱싱과 슬라이싱 

In [77]:
d=np.arange(12).reshape(2, 2, 3)
print(d, d.shape)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]] (2, 2, 3)


In [78]:
# 3차원 배열의 인덱싱
print(d[0][0][0]) # 0면 0행 0열 인덱싱
print(d[0, 0, 0]) # 0면 0행 0열 인덱싱
print(d[0, 1, 2]) # 0면 1행 2열 인덱싱

0
0
5


In [79]:
# 3차원 배열의 슬라이싱
print(d[:,:-1,:-1])

[[[0 1]]

 [[6 7]]]


In [80]:
print(d[:,1:,1:])

[[[ 4  5]]

 [[10 11]]]


In [81]:
print(d[:,:,-1])

[[ 2  5]
 [ 8 11]]


In [82]:
print(d[:,-1,-1])
print(d[-1,-1,-1])

[ 5 11]
11


In [83]:
a=np.arange(12)
print(a, a.shape)
print(a[0]) # 스칼라
print(a[0:1]) # 배열(ndarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
0
[0]


##4. 불 인덱싱
-조건문 필터링

In [84]:
import numpy as np
a=np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [85]:
print(a>2)

[False False  True  True  True  True]


In [86]:
print(a[a>2])

[3 4 5 6]


##5. 조건 필터
- 비교 연산을 통해서 "True" 값만 추출한다!

In [87]:
a=np.array([1, 2, 3, 4, 5, 6])
result=a>2
result

array([False, False,  True,  True,  True,  True])

In [88]:
a[a>2]

array([3, 4, 5, 6])

In [89]:
a[a!=3]

array([1, 2, 4, 5, 6])

In [90]:
print(a[(a>2) & (a<6)]) # 2보다 크고 6보다 작은 요소만 추출
print(a[a % 2==0]) # 2로 나눈 나머지가 0인 요소만 추출
print(a[a<a.mean( )]) # 평균보다 작은 값만 추출

[3 4 5]
[2 4 6]
[1 2 3]


In [91]:
# 데이터 핸들링 할 때, 그대로 적용
print(a[True])
print(a[False])

[[1 2 3 4 5 6]]
[]


#Section 04. 넘파이 배열의 정렬
##1 기본 정렬: sort 함수

In [92]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)
r=np.sort(a) # 원본 변경 없이 오름차순 정렬
print(r, a)

[2 8 9 7 3 1 4 5 6] (9,)
[1 2 3 4 5 6 7 8 9] [2 8 9 7 3 1 4 5 6]


In [93]:
# 오름차순 정렬
a.sort()
print(a)

[1 2 3 4 5 6 7 8 9]


In [94]:
# 내림차순 정렬
r=np.sort(a)[::-1]
print(r)

[9 8 7 6 5 4 3 2 1]


##2. 인덱스 반환 정렬: argsort 함수

In [95]:
a=np.array([2, 8, 9, 7, 3, 1, 4, 5, 6])
print(a, a.shape)

[2 8 9 7 3 1 4 5 6] (9,)


In [96]:
np.argsort(a)

array([5, 0, 4, 6, 7, 8, 3, 1, 2])

In [97]:
sort_index=np.argsort(a)
print(sort_index)

[5 0 4 6 7 8 3 1 2]


##3. 2차원 배열의 정렬

In [98]:
arr2d=np.array([[5, 6, 7, 8],
 [4, 3, 2, 1],
 [10, 9, 12, 11]])
print(arr2d)
print(arr2d.shape)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
(3, 4)


In [99]:
# 열 방향으로 같은 행의 요소 정렬
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [100]:
# 행 방향으로 같은 열의 요소 정렬
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [101]:
# 열 방향으로 같은 행 정렬
print(arr2d)
print(np.sort(arr2d))
np.argsort(arr2d, axis=1)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]


array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [102]:
# 행 방향으로 같은 열 정렬
print(arr2d)
print(np.sort(arr2d, axis=0))
np.argsort(arr2d, axis=0)

[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
[[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

#Section 05. 넘파이 배열의 연산
## 1. 넘파이 배열의 연산
### 배열 내 요소들의 연산

In [103]:
# 같은 배열 내 요소의 합 구하기
import numpy as np
a=np.array([[1, 2, 3],
 [4, 5, 6]])
np.sum(a, axis=0), np.sum(a, axis=1)

(array([5, 7, 9]), array([ 6, 15]))

In [104]:
a.sum()

np.int64(21)

###배열과 상수의 사칙연산

In [105]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=2
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [106]:
A=np.arange(1, 13).reshape(3, 4)
print(A+10)
print(A-10)
print(A*10)
print(A/10)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]


In [107]:
A=np.arange(1, 13).reshape(3, 4)
A-1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 배열과 배열의 요소 간 연산

In [108]:
a=np.array([[1, 2, 3],
 [4, 5, 6]])
b=np.array([1, 2, 3]) # b=np.array([[1, 2, 3]])도 가능
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


###배열 간의 곱셈과 행렬 곱셈의 차이

In [109]:
a=np.array([[1, 2],
 [3, 4]])
b=np.array([[1, 2],
 [1, 2]])
print(a*b)
print(a.dot(b))

[[1 4]
 [3 8]]
[[ 3  6]
 [ 7 14]]


##2. 브로드캐스팅

In [110]:
A=np.array([[1, 2, 0],[3, 4, 0]])
B=np.array([1, 2, 3])
A+B

array([[2, 4],
       [4, 6]])

In [113]:
A.shape, B.shape

((2, 3), (2, 1))

In [111]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([2])
A+B

array([[3, 4, 5],
       [6, 7, 8]])

In [112]:
A=np.array([[1, 2, 3],
 [4, 5, 6]])
B=np.array([[2],
 [4]])
A+B

array([[ 3,  4,  5],
       [ 8,  9, 10]])